export { default as MyPage } from '@/pages/MyPage/MyPage';
export { default as Notification } from '@/pages/MyPage/Notification';
export { default as ConfirmPassword } from '@/pages/MyPage/ConfirmPassword';
export { default as EditProfile } from '@/pages/MyPage/EditProfile';
export { default as ChangePassword } from '@/pages/MyPage/ChangePassword';
export { default as WishList } from '@/pages/MyPage/WishList';
export { default as WishListMore } from '@/pages/MyPage/WishListMore';
export { default as TripPoint } from '@/pages/MyPage/TripPoint';
export { default as Faq } from '@/pages/MyPage/Faq';
